apiVersion: apps/v1
kind: Deployment
metadata:
  name: vultture-search-snippet
  namespace: vultture
spec:
  selector:
    matchLabels:
      app: vultture-search-snippet-app
      version: "1"
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: vultture-search-snippet-app
        version: "1"
    spec:
      containers:
        - name: vultture-search-snippet-container
          image: harbor.qmhtech.com/qmhdocker/vultturesnippet:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
      imagePullSecrets:
        - name: regcred
