apiVersion: v1
kind: Service
metadata:
  name: vultture-search-snippet-svc
  namespace: vultture
spec:
  selector:
    app: vultture-search-snippet-app
  ports:
    - protocol: TCP
      name: http
      port: 8090
      targetPort: 3000
  type: NodePort
